# Generated by Django 4.2.26 on 2025-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bowler_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='bowler_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='bowler_overs',
            field=models.CharField(blank=True, default='0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='bowler_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='bowler_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='striker_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='striker_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='striker_runs',
            field=models.IntegerField(default=0),
        ),
    ]
