# Generated by Django 4.2.26 on 2026-04-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_match_bowler_balls_match_bowler_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
