# Generated by Django 4.2.26 on 2026-04-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_match_current_innings_match_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='dismissed_players',
            field=models.TextField(blank=True, default=''),
        ),
    ]
