# Generated by Django 4.2.26 on 2026-04-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_match_dismissed_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField(default=1)),
                ('over_number', models.IntegerField(default=0)),
                ('ball_number', models.IntegerField(default=1)),
                ('striker', models.CharField(max_length=200)),
                ('non_striker', models.CharField(max_length=200)),
                ('bowler', models.CharField(max_length=200)),
                ('runs', models.IntegerField(default=0)),
                ('extra_type', models.CharField(blank=True, max_length=10, null=True)),
                ('is_wicket', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='scores.match')),
            ],
        ),
    ]
